collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6484972
color:
  saturation: 0.5493458
  brandStrength: 0.6264806
  lightness: 0.7611788
  brandColors:
    - '#E11E1D'
    - '#910C0E'
    - '#F0EBE1'
    - '#878078'
    - '#FFAB9A'
  rhythmicContrast: 0.08344916
layout_spectrum: 0.2978864
name: Mercadillo
